// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRx6URJhjECuns2AZAMWvpoID7IutBxGs',
    appId: '1:1009046445553:web:5a8238277f79b3ec9cf850',
    messagingSenderId: '1009046445553',
    projectId: 'smartmentor-26ab4',
    authDomain: 'smartmentor-26ab4.firebaseapp.com',
    storageBucket: 'smartmentor-26ab4.firebasestorage.app',
    measurementId: 'G-9TV90TVBFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbjnMbsjzJQpiIrflhxlVoDulDW8bSdaY',
    appId: '1:1009046445553:android:2ad89b266acc673c9cf850',
    messagingSenderId: '1009046445553',
    projectId: 'smartmentor-26ab4',
    storageBucket: 'smartmentor-26ab4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZKPp-ghDQr7rBa4KNVlfNwUaenvJi7Qw',
    appId: '1:1009046445553:ios:97a55b74c54e0bc89cf850',
    messagingSenderId: '1009046445553',
    projectId: 'smartmentor-26ab4',
    storageBucket: 'smartmentor-26ab4.firebasestorage.app',
    iosBundleId: 'com.smartmentor.smartMentor',
  );
}
